# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_perm_rev_cpp <- function(downNode_rev, outlet) {
    .Call(`_rivnet_init_perm_rev_cpp`, downNode_rev, outlet)
}

path_vel_cpp <- function(OCN, str = "RN", includeDownstreamNode = FALSE) {
    .Call(`_rivnet_path_vel_cpp`, OCN, str, includeDownstreamNode)
}

